"""add wallet table

Revision ID: 29651b1e91a1
Revises: 5503444b5dda
Create Date: 2025-07-08 10:09:11.133015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29651b1e91a1'
down_revision: Union[str, Sequence[str], None] = '5503444b5dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'wallet',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('balance', sa.Float, nullable=False, default=0),
        sa.Column('icon_name', sa.String(length=64), nullable=True),
        sa.Column('color_hex', sa.String(length=16), nullable=True),
        sa.Column('currency', sa.String(length=8), nullable=False, default='KZT'),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('user.id'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    # ### end Alembic commands ###
