"""add_reminder_fields_to_goal

Revision ID: 48d7f741f033
Revises: eaca9687e7ac
Create Date: 2025-07-23 02:49:28.365470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d7f741f033'
down_revision: Union[str, Sequence[str], None] = 'eaca9687e7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('reminder_period', sa.String(), nullable=True))
    op.add_column('goal', sa.Column('selected_weekday', sa.Integer(), nullable=True))
    op.add_column('goal', sa.Column('selected_month_day', sa.Integer(), nullable=True))
    op.add_column('goal', sa.Column('selected_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'selected_time')
    op.drop_column('goal', 'selected_month_day')
    op.drop_column('goal', 'selected_weekday')
    op.drop_column('goal', 'reminder_period')
    # ### end Alembic commands ###
