"""add reset_password_token fields to user

Revision ID: 5e7cbbec59f2
Revises: 7d5e1ca36480
Create Date: 2025-07-16 14:34:11.623220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7cbbec59f2'
down_revision: Union[str, Sequence[str], None] = '7d5e1ca36480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('income', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.add_column('user', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('reset_password_token_sent_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_reset_password_token'), 'user', ['reset_password_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reset_password_token'), table_name='user')
    op.drop_column('user', 'reset_password_token_sent_at')
    op.drop_column('user', 'reset_password_token')
    op.alter_column('income', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('expense', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ###
