"""Make category_id and wallet_id nullable in expense and income

Revision ID: 620d37fb6be3
Revises: a293e052f553
Create Date: 2025-07-13 17:36:13.872647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620d37fb6be3'
down_revision: Union[str, Sequence[str], None] = 'a293e052f553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('income', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('income', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
