"""add name icon color to transaction

Revision ID: 6757f8327801
Revises: b032447257ee
Create Date: 2025-07-15 17:38:57.440952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6757f8327801'
down_revision: Union[str, Sequence[str], None] = 'b032447257ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('name', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('color', sa.String(), nullable=True))
    op.drop_constraint('transaction_to_wallet_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_from_wallet_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'wallet', ['to_wallet_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'wallet', ['from_wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_from_wallet_id_fkey', 'transaction', 'wallet', ['from_wallet_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('transaction_to_wallet_id_fkey', 'transaction', 'wallet', ['to_wallet_id'], ['id'], ondelete='SET NULL')
    op.drop_column('transaction', 'color')
    op.drop_column('transaction', 'icon')
    op.drop_column('transaction', 'name')
    # ### end Alembic commands ###
