"""add wallet_name to transaction

Revision ID: 7d5e1ca36480
Revises: c992eec80517
Create Date: 2025-07-16 04:13:33.293795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5e1ca36480'
down_revision: Union[str, Sequence[str], None] = 'c992eec80517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('wallet_name', sa.String(), nullable=True))
    op.drop_constraint('transaction_from_wallet_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_to_wallet_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'wallet', ['from_wallet_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'wallet', ['to_wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_to_wallet_id_fkey', 'transaction', 'wallet', ['to_wallet_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('transaction_from_wallet_id_fkey', 'transaction', 'wallet', ['from_wallet_id'], ['id'], ondelete='SET NULL')
    op.drop_column('transaction', 'wallet_name')
    # ### end Alembic commands ###
