"""Add category table

Revision ID: 90bdc7133cef
Revises: b8e1ed5a49dd
Create Date: 2025-06-22 09:36:30.346861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "90bdc7133cef"
down_revision: Union[str, Sequence[str], None] = "b8e1ed5a49dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("defaultcategory")
    op.create_index(op.f("ix_category_name"), "category", ["name"], unique=False)
    op.drop_column("category", "icon")
    op.drop_column("category", "created_at")
    op.drop_column("category", "is_default")
    op.drop_constraint("user_google_id_key", "user", type_="unique")
    op.create_index(
        op.f("ix_user_email_verification_token"),
        "user",
        ["email_verification_token"],
        unique=False,
    )
    op.create_index(op.f("ix_user_google_id"), "user", ["google_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_google_id"), table_name="user")
    op.drop_index(op.f("ix_user_email_verification_token"), table_name="user")
    op.create_unique_constraint("user_google_id_key", "user", ["google_id"])
    op.add_column(
        "category",
        sa.Column("is_default", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "category",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "category", sa.Column("icon", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_category_name"), table_name="category")
    op.create_table(
        "defaultcategory",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("expense", "income", name="categorytype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("icon", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="defaultcategory_pkey"),
    )
    # ### end Alembic commands ###
