"""add_apple_id_to_user

Revision ID: 93b9afd1280a
Revises: 5e7cbbec59f2
Create Date: 2025-07-18 09:59:41.249062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b9afd1280a'
down_revision: Union[str, Sequence[str], None] = '5e7cbbec59f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apple_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['apple_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'apple_id')
    # ### end Alembic commands ###
