"""add icon_color_currency_to_goal_income_expense

Revision ID: a293e052f553
Revises: cb4c4a8c5ee7
Create Date: 2025-07-13 08:21:55.006956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a293e052f553'
down_revision: Union[str, Sequence[str], None] = 'cb4c4a8c5ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    op.add_column('expense', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    op.add_column('expense', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    op.add_column('goal', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    op.add_column('goal', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    op.add_column('goal', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="KZT"))
    op.add_column('income', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    op.add_column('income', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    op.add_column('income', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income', 'color')
    op.drop_column('income', 'icon')
    op.drop_column('income', 'name')
    op.drop_column('goal', 'currency')
    op.drop_column('goal', 'color')
    op.drop_column('goal', 'icon')
    op.drop_column('expense', 'color')
    op.drop_column('expense', 'icon')
    op.drop_column('expense', 'name')
    # ### end Alembic commands ###
