"""change category enum to varchar

Revision ID: af338e697732
Revises: 90bdc7133cef
Create Date: 2025-06-22 13:06:54.483463

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af338e697732"
down_revision: Union[str, Sequence[str], None] = "90bdc7133cef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category",
        "type",
        existing_type=postgresql.ENUM("expense", "income", name="categorytype"),
        type_=sa.Enum("INCOME", "EXPENSE", name="categorytype", native_enum=False),
        nullable=True,
    )
    op.drop_index("ix_user_google_id", table_name="user")
    op.create_index(op.f("ix_user_google_id"), "user", ["google_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_google_id"), table_name="user")
    op.create_index("ix_user_google_id", "user", ["google_id"], unique=True)
    op.alter_column(
        "category",
        "type",
        existing_type=sa.Enum(
            "INCOME", "EXPENSE", name="categorytype", native_enum=False
        ),
        type_=postgresql.ENUM("expense", "income", name="categorytype"),
        nullable=False,
    )
    # ### end Alembic commands ###
