"""set ON DELETE SET NULL for wallet_id in transaction

Revision ID: c992eec80517
Revises: ccd60aafd002
Create Date: 2025-07-16 03:37:31.082587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c992eec80517'
down_revision: Union[str, Sequence[str], None] = 'ccd60aafd002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_to_goal_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_from_goal_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'goal', ['from_goal_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'goal', ['to_goal_id'], ['id'])
    # Удаляем старые ограничения на кошельки
    op.drop_constraint('transaction_from_wallet_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_to_wallet_id_fkey', 'transaction', type_='foreignkey')
    # Создаём новые с ON DELETE SET NULL
    op.create_foreign_key(
        'transaction_from_wallet_id_fkey',
        'transaction', 'wallet',
        ['from_wallet_id'], ['id'],
        ondelete='SET NULL'
    )
    op.create_foreign_key(
        'transaction_to_wallet_id_fkey',
        'transaction', 'wallet',
        ['to_wallet_id'], ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_from_goal_id_fkey', 'transaction', 'goal', ['from_goal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('transaction_to_goal_id_fkey', 'transaction', 'goal', ['to_goal_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('transaction_from_wallet_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_to_wallet_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(
        'transaction_from_wallet_id_fkey',
        'transaction', 'wallet',
        ['from_wallet_id'], ['id']
    )
    op.create_foreign_key(
        'transaction_to_wallet_id_fkey',
        'transaction', 'wallet',
        ['to_wallet_id'], ['id']
    )
    # ### end Alembic commands ###
