"""add created_at to user

Revision ID: cb4c4a8c5ee7
Revises: eb9f58116686
Create Date: 2025-07-12 18:55:59.292059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb4c4a8c5ee7'
down_revision: Union[str, Sequence[str], None] = 'eb9f58116686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_wallet_id', sa.Integer(), nullable=True),
    sa.Column('to_wallet_id', sa.Integer(), nullable=True),
    sa.Column('from_goal_id', sa.Integer(), nullable=True),
    sa.Column('to_goal_id', sa.Integer(), nullable=True),
    sa.Column('from_category_id', sa.Integer(), nullable=True),
    sa.Column('to_category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['from_category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['from_goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['from_wallet_id'], ['wallet.id'], ),
    sa.ForeignKeyConstraint(['to_category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['to_goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['to_wallet_id'], ['wallet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('expense', 'transaction_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('expense', 'type')
    op.drop_column('expense', 'category_name')
    op.alter_column('income', 'transaction_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('income', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('income', 'type')
    op.drop_column('income', 'category_name')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.add_column('income', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('income', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('income', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('income', 'transaction_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('expense', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('expense', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('expense', 'transaction_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_table('transaction')
    # ### end Alembic commands ###
