"""set ondelete=cascade for all user-related foreign keys

Revision ID: eaca9687e7ac
Revises: c9ba08d33fd8
Create Date: 2025-07-23 01:27:06.015727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaca9687e7ac'
down_revision: Union[str, Sequence[str], None] = 'c9ba08d33fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_from_goal_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_to_goal_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'goal', ['from_goal_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'goal', ['to_goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_to_goal_id_fkey', 'transaction', 'goal', ['to_goal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('transaction_from_goal_id_fkey', 'transaction', 'goal', ['from_goal_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
