"""add goal_name to transaction

Revision ID: eb6f7990bfc4
Revises: 6757f8327801
Create Date: 2025-07-16 02:31:17.986073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6f7990bfc4'
down_revision: Union[str, Sequence[str], None] = '6757f8327801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('goal_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'goal_name')
    # ### end Alembic commands ###
